version: '3.1'
services:
  notes-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MONGODB_URL=${MONGODB_URL}
    ports:
      - 3000:${PORT}
