name: Bombard deployed server on 
run-name: perform stress-tests on the API
on: [push]
jobs:
    bombard-get:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - run: npm install
            - run: sleep 100
            - run: npm run start-bombard-get
    bombard-post:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - run: npm install
            - run: sleep 100
            - run: npm run start-bombard-post